### ISSUE TITLE
Right file extensions

### ISSUE THREAD

**Issue by airsynth** [yomboprime/colorator#2]
When operating with files the extension should be replaced according to the selected file format.

**Comment by yomboprime** [comment]
What extensions should be set for these?:
- Colorator Hi-res native format file
- Only Hi-res colour attributes file

Perhaps `.col` and `.colattr`?

**Comment by airsynth** [comment]
.col is too common. The other one is good.

**Comment by yomboprime** [comment]
Ok, `.colorator` and `.colattr` then.
