### ISSUE TITLE
Sprite export extrange format in "selected blocks" mode

### ISSUE THREAD

**Issue by Hamberthm** [yomboprime/colorator#4]
Hello! I developed a routine for displaying the sprites exported from the "ZXB format 1x1" just fine.

However, when I select the option "ZXB format, selected blocks" the byte arrangement of the output file is totally different to that on the format 1x1, that is, bytes read in character blocks from top to bottom and then the next one to the right.

Is there a way to export a format identical to the "ZXB format 1x1" but just for selected blocks??

Thanks!

**Comment by yomboprime** [comment]
Hi! Thanks for reporting.

Should be fixed now, can you retry?

**Comment by Hamberthm** [comment]
Thanks for the quick response! I really love this project! Sadly now I cannot run the application, it gives me the following error and I'm not shure if it's me or the compiler's fault:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Colorator has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```


Sorry that I'm not that familiar with Java (I'm only studying Z80 assembly lol)

**Comment by yomboprime** [comment]
What is your system? A Windows machine?
Can you please enter in a terminal window and enter:
```java --version```

**Comment by Hamberthm** [comment]
Sure, it's a Windows 10 64 bit system:

`C:\Users\Humberto Möckel\Desktop\colorator-master\bin>java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)`

**Comment by yomboprime** [comment]
Probably it will work if you install a newer Java environment. For example try the latest JDK here: http://jdk.java.net/16/

**Comment by Hamberthm** [comment]
Thanks, that did the trick. However, my original issue is still there.  I'll further explain myself; I have made a 5x2 block simple drawing. I've also made a ZX routine to display it block per block, based on the "ZXB 1x1" export sprite format. It copies the first byte, then the second going down on the character block, and when it reaches the 8th one it switches to the next char to the right. That is exactly how the ZXB 1x1 format is exported.
However, if I select "ZXB format, selected blocks", and then select the blocks of my drawing prior to exporting, the exported bytes are totally differnt.

This is the output using ZXB 1x1 (I deleted all the 0's from all the other blocks to get essentially what I want):

`0,0,0,0,3,1c,f0,9f,0,0,0,ff,cb,a,a,fb,0,0,0,fe,81,1c,23,ff,0,0,0,0,80,60,18,f7,0,0,0,0,0,0,0,c0,80,80,e1,39,77,1,0,0,2,f1,8,8,f,98,f0,0,0,0,80,ff,ff,0,0,0,20,67,4c,88,f8,c,7,0,7e,83,c1,47,78,c0,80,0,0,0,0,0,0,0,0,0,0,0`

This is the resulting image using my routine: [https://1drv.ms/u/s!AlKre4_rNmpJh6Eb6va_uaQtDY0bcw?e=5cEGKF](https://1drv.ms/u/s!AlKre4_rNmpJh6Eb6va_uaQtDY0bcw?e=5cEGKF)

And this is the output using ZXB Selected Blocks:

`3,2,2,7,5,5,9,9,19,19,11,11,1f,10,1f,19,e0,28,38,18,10,8,8,3c,46,42,42,46,3c,8,88,48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0`

And now it looks like this: [https://1drv.ms/u/s!AlKre4_rNmpJh6EaNHwf6OezDKxC9w?e=oYXTTz](https://1drv.ms/u/s!AlKre4_rNmpJh6EaNHwf6OezDKxC9w?e=oYXTTz)


So, what I want essentially is the option to select only the blocks that I want and get the same result that I shared above, that is, the same as ZXB 1x1 with all the data from the other blocks removed. Here is the SCR I'm using in case it is needed: [https://1drv.ms/u/s!AlKre4_rNmpJh6EcqVRJ3qGyi2AE7A?e=vUPd7A](
https://1drv.ms/u/s!AlKre4_rNmpJh6EcqVRJ3qGyi2AE7A?e=vUPd7A)

**Comment by yomboprime** [comment]
Can you retry? Now it should work OK, I've tested it.

**Comment by Hamberthm** [comment]
Thank you so so much!!! I can now export the blocks that I want with the same format as 1x1 ZXB. 

Is there a way to include the color attributes in the same file for those blocks? (Maybe a feature for future releases). 

Thanks again!! :D I can now continue making my graphic engine :P

**Comment by yomboprime** [comment]
Thank you for using Colorator, it's nice to have people interested after a long time. It is a project I made with tons of love and care :-)

I'll see what I can do with the attributes...

**Comment by yomboprime** [comment]
@Hamberthm I've added the attributes bytes for both exporting options. They are at the end of the file, one attribute per line.

Please try ;-)

**Comment by Hamberthm** [comment]
Wow! Such good treatment :D Thanks! That makes Colorator a really powerful and comfortable tool for developing games and graphics/sprites in general. Now I can design sprites and export and format them easily to fit in memory for my project. It's so cool because it enables me to focus in learning assembly code/spectrum architecture and saves me a TON of time than doing test sprites by hand.  I don't think I'm going to make anything impressive, I'm just learning, but if I can get it to something distributable or merely useful, then Colorator and you will be in the credits!

Gracias y un saludo desde Argentina!! Soy Humberto y recientemente un amigo me regaló dos "CZ" Spectrums, la versión licenciada argentina. Mi primera aproximación a hardware clásico, me encanta la comunidad que hay alrededor de él. :D

**Comment by yomboprime** [comment]
Un placer. Saludos ^__^

Si tienes más sugerencias o encuentras más bugs ya sabes.
